### ISSUE TITLE
bintray is closed.

### ISSUE THREAD

**Issue by jackystd** [jinq0123/grpc-lua#10]
run "conan create . user/channel --build missing" on mac and be required to login with username:

`Please log in to "remote_bintray_jinq0123" to perform this action. Execute "conan user" command.
`

How can i create it on my mac?

**Comment by wxy2wxh** [comment]
I have the same problem.

Please log in to "remote_bintray_jinq0123" to perform this action. Execute "conan user" command.
Remote 'remote_bintray_jinq0123' username:
How to register the username?

**Comment by jinq0123** [comment]
Sorry. conan is broken because bintray is closed.

**Comment by gonsalez-ru** [comment]
Possible wokaround.
1) Use next remotes with premake:
conan remote add conan-legacy-conan-community https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-conan-community
conan remote add conan-legacy-bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-bincrafters
conan remote add conan-legacy-inexorgame https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-inexorgame
conan remote add bintray-conan https://bincrafters.jfrog.io/artifactory/api/conan/bintray-conan/
2) While jinq's dependent modules are absent at bincrafters.jfrog.io, you can prebuld them and localy share with "conan export"

**Comment by zihuan-dm** [comment]
> Sorry. conan is broken because bintray is closed.

![image](https://user-images.githubusercontent.com/5344858/152759577-2d298b04-b383-427a-b985-81896b2465eb.png)
jinq您好！我在执行conan_install.bat的时候报出这样的错误，你的意思是不是远程仓库被关闭了？

**Comment by jinq0123** [comment]
对
