### ISSUE TITLE
Lua 5.1 / LuaJIT support

### ISSUE THREAD

**Issue by rurounijones** [jinq0123/grpc-lua#5]
Attempting to run the examples with Lua52, Lua51 and LuaJIT result in the examples hanging or crashing.

Is there any possibility of supporting lua51 release which will also add support for the popular and the very fast http://luajit.org/ lua implementation?

I am relatively new to the lua ecosystem so I am not sure how difficult this will be (although I am assuming it is not trivial amount of work given the number of dependencies etc.). 

Based on https://github.com/martanne/vis/issues/291 it looks like it could be possible to get LuaJit compatible with 5.2 although most applications of luaJit would probably not be using this patch.

**Comment by rurounijones** [comment]
If you think it should be easy then I will have a look and see if I can make the changes. If you have any starting points / advice that would be useful. Thanks for the info.

**Comment by jinq0123** [comment]
I add a section [TODO: Integrate into Unity](https://github.com/jinq0123/grpc-lua#todo-integrate-into-unity) in README.

**Comment by rurounijones** [comment]
Thanks for the information.

I will have a look but since I am completely new to lua and the ecosystem in general ~~I am happy to sponsor this feature to $200 if anyone can do it to @jinq0123 satisfaction and get it merged.~~

Edit: I am using a different RPC system for the moment which does the job. ~~I would be interested in sponsoring any work to get this working in 5.1 in an environment (Specifically the Mission Scripting Encironment of the game DigitalCombatSimulator) where the GRPC server is not the main event loop.~~

**Comment by thefosk** [comment]
Any updates?

**Comment by 4mig4** [comment]
Wondering the same
